### ISSUE TITLE
problem about reproducing Copa

### ISSUE THREAD

**Issue by liujingbbd** [venkatarun95/genericCC#3]
Hi genericCC team,

The problem I meet is that when I run my command as ​​the terminal shows, the Copa only run 3 seconds and exited. However, I run the similar command as the figure shows for Remy, it works well.

![screenshot from 2018-04-09 15-33-15](https://user-images.githubusercontent.com/16717748/38486668-4456afb6-3c10-11e8-98e1-92a87867ee6e.png)

So, my command for Copa is right or not? Or, there are other bugs?

Thank you for your any response​​.​​

Jing Liu

**Comment by venkatarun95** [comment]
Hi Jing Liu

Thank you for your interest in Copa. We had been experimenting with several `delta_conf` types before finalizing on the `auto` mode that switches between delay-sensitive and competitive modes. We don't maintain the other modes anymore. Sorry about that. Currently the following are supported:

`do_ss:auto:0.5`  -  Detects TCP and automatically switches between the two modes below
`do_ss:constant_delta:0.5` - delta is always 0.5 - good for maintaining low delay in the absence of buffer-filling flows
`do_ss:tcp_coop` - delta is modulated at runtime to be competitive with buffer-filling flows (eg. TCP cubic)

`0.5` can be replaced with any value. This will be used as the default value of delta. Copa tries to maintain 1/delta packets in the queue. Lower values of delta will lead to higher throughput and higher delay. Values greater than 1 will lead to link underutilization. The recommended default value is 0.5, as that maintains 2 packets in the queue at equilibrium. Setting delta = 1 is treading too close to the line and will lead to under-utilization if the network jitters packets or pacing is imperfect.

`do_ss:` instructs Copa to perform slow start. We were also experimenting with a fast startup mechanism that sought to move to the right rate in constant time. It is unsafe and not thoroughly tested. If you want to play with the feature, uncomment lines 167-169 in markoviancc.cc and remove line 166
