### ISSUE TITLE
Running copa (cctype=markoviancc) results in seg fault

### ISSUE THREAD

**Issue by shivariyer** [venkatarun95/genericCC#5]
Hi Venkat,

I am trying to run some expts with Copa for one of our paper revisions. However, Copa fails with a seg fault regardless of the delta_type used. Here are the console dumps from two different runs (I had `./receiver` running in another terminal window for both these runs):

    shivar@shivar-desktop: Tue May 04 20:01  genericCC $ ./sender serverip=localhost cctype=markovian offduration=0 onduration=60000 delta_conf=do_ss:auto:0.5 traffic_params=deterministic,num_cycles=1
    Using MarkovianCC.
    Will do slow start
    Using Automatic Mode with default delta = 0.5
    Assigning Source ID: 1350333981
    Assuming training link rate of: 2666.67 pkts/sec
    inet_aton failed while sending data. Code: 0
    Set min. RTT to 0.096192
    Connection Established.
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    Segmentation fault (core dumped)
    shivar@shivar-desktop: Tue May 04 20:01  genericCC $ ./sender serverip=localhost cctype=markovian delta_conf=constant_delta:1
    Using MarkovianCC.
    Constant delta mode with delta = 1
    Assigning Source ID: 1536865633
    Assuming training link rate of: 2666.67 pkts/sec
    inet_aton failed while sending data. Code: 0
    Set min. RTT to 0.155211
    Connection Established.
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    inet_aton failed while sending data. Code: 0
    Segmentation fault (core dumped)

All this time, the receiver doesn't print anything. It's a blank screen on the receiver terminal. 

I am using 64-bit machine with Ubuntu 18.04 (kernel version 4.19.0-0419000-generic), g++ 7.5.0 and makepp 2.0.98.5.

This issue didn't happen in the summer of last year. It ran smoothly then. Three of us in our group (in three geographically different locations) have been facing the same issue for the last few months now. 

Is this something that can be fixed quickly? Or any pointers?

Thanks! 

Regards,
Shiva

**Comment by venkatarun95** [comment]
I was able to reproduce your issue and fixed it by saying "127.0.0.1" in the binary invocation. I don't think inet_aton understands "localhost". Does this work for you as well?

**Comment by shivariyer** [comment]
Hi Venkat, thanks for your response! The problem still persists. Here's the output.

    shivar@Lakshmi-TravelMate-P648-M: genericCC $ ./sender serverip=127.0.0.1 cctype=markovian delta_conf=constant_delta:1
    Using MarkovianCC.
    Constant delta mode with delta = 1
    Assigning Source ID: 1718909887
    Assuming training link rate of: 2666.67 pkts/sec
    Set min. RTT to 0.161273
    Connection Established.
    Segmentation fault (core dumped)

I also tried running the sender inside mahimahi (which is what we ultimately want) like this.

    shivar@Lakshmi-TravelMate-P648-M: genericCC $ mm-delay 10
    [delay 10 ms] shivar@Lakshmi-TravelMate-P648-M: genericCC $ ./sender serverip=100.64.0.1 cctype=markovian delta_conf=constant_delta:1
    Using MarkovianCC.
    Constant delta mode with delta = 1
    Assigning Source ID: 574193848
    Assuming training link rate of: 2666.67 pkts/sec
    Set min. RTT to 20.8086
    Connection Established.
    Segmentation fault (core dumped)

Any other pointers?

Thanks,
Shiva

**Comment by venkatarun95** [comment]
Please use `delta_conf=do_ss:auto:0.5` or `delta_conf=do_ss:constant_delta:0.5`. The `do_ss` is necessary (do slow start). Not having it implies "fast start", which I had disabled since it is no good

**Comment by ccwutw** [comment]
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG1mnhlh/vsyvUvSIMnyUwiBbIecKdTy4RSrkf6a9+Yn ccw@es.aau.dk

**Comment by shivariyer** [comment]
Hi Venkat, I am sorry but the problem still persists! 

    [delay 10 ms] shivar@Lakshmi-TravelMate-P648-M: genericCC $ ./sender serverip=100.64.0.1 cctype=markovian delta_conf=do_ss:constant_delta:0.5
    Using MarkovianCC.
    Will do slow start
    Constant delta mode with delta = 0.5
    Assigning Source ID: 1921433170
    Assuming training link rate of: 2666.67 pkts/sec
    Set min. RTT to 20.7636
    Connection Established.
    Segmentation fault (core dumped)

We poked around a bit using `gdb` to find out where the problem was happening. Curiously, when stepping line by line in gdb, I observe that some output is printed. In line 95 of `traffic-generator.hh`, there is a call to `_ctcp.send_data()`. If I step over that call, it results in a SIGSEGV. But if I step into the function, then output is printed showing zero throughput. See below.

    310       double throughput = transmitted_bytes/( cur_time / 1000.0 );                                                                        
    (gdb)                                                                                                                                         
    311       double delay = (delay_sum / 1000) / num_packets_transmitted;                      
    (gdb)                                                                                                                     
    313       std::cout<<"\n\nData Successfully Transmitted\n\tThroughput: "<<throughput<<" bytes/sec\n\tAverage Delay: "<<delay<<" sec/packet\n\t
    Completion time: " << cur_time / 1000.0 << "sec\n";                                                                                           
    (gdb)                                                                                                                                         
                                                                                     
                                                                                                                                              
    Data Successfully Transmitted                                         
            Throughput: 0 bytes/sec
            Average Delay: -nan sec/packet
            Completion time: 23.0127sec
    315       double avg_throughput = tot_bytes_transmitted / ( tot_time_transmitted / 1000.0);
    (gdb)
    ...
    317       std::cout<<"\n\tAvg. Throughput: "<<avg_throughput<<" bytes/sec\n\tAverage Delay: "<<avg_delay<<" sec/packet\n";
    (gdb)
    
            Avg. Throughput: 0 bytes/sec
            Average Delay: -nan sec/packet
    319       if( LINK_LOGGING )
    (gdb)
    168       ofstream link_logfile;
    (gdb)
    321     }
    (gdb)
    TrafficGenerator<CTCP<MarkovianCC> >::send_data (this=0x7fffffffaed0, seed=<optimized out>, id=322686329) at traffic-generator.hh:98
    98                      std::cout<<"Sender: "<<id<<", Flow: "<<flow_id<<". Transmitted for "<<on_duration<<(byte_switched?"   bytes.":" ms.")<<endl<<std::flush;
    (gdb)
    ...

As you can see, throughput is zero, but at least something was printed. So the next time, I stepped over the `send_data()` function in `sender.cc` without entering the function, and this is what happened.

    94                      bool byte_switched = (_switch_type == SwitchType::BYTE_SWITCHED);
    (gdb)
    95                      _ctcp.send_data(on_duration, byte_switched, flow_id, id);
    (gdb)
    Assuming training link rate of: 2666.67 pkts/sec
    Set min. RTT to 0.122064
    Connection Established.
    
    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff747bfa3 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

**Comment by venkatarun95** [comment]
I'm unable to reproduce the issue. The command you suggested works for me. One thing to try is to also use an mm-link shell to limit the speed to reasonable amounts. If that doesn't work, we can hop on a call and see what's going on

**Comment by shivariyer** [comment]
Nope still doesn't work for me :( 

Thanks, will be happy to get on a call.

**Comment by venkatarun95** [comment]
@xudongliao faced a similar problem and they found a fix that works for them (I couldn't reproduce their problem either). Does the fix work for you as well? It has been merged into master
